-- Create quotes table
CREATE TABLE IF NOT EXISTS quotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  author TEXT NOT NULL,
  category TEXT DEFAULT 'Lainnya',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  is_approved BOOLEAN DEFAULT false
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_quotes_created_at ON quotes(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quotes_is_approved ON quotes(is_approved);

-- Enable Row Level Security
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;

-- Allow public to read approved quotes
CREATE POLICY "Public can read approved quotes"
ON quotes FOR SELECT
TO public
USING (is_approved = true);

-- Allow public to insert quotes (they need to be approved by admin)
CREATE POLICY "Public can insert quotes"
ON quotes FOR INSERT
TO public
WITH CHECK (true);

-- Insert dummy quotes
INSERT INTO quotes (text, author, category, is_approved) VALUES
  ('Hari ini mungkin berat, tapi kamu sudah sampai di sini — dan itu sudah lebih dari cukup.', 'Kelas Pekerja', 'Kehidupan', true),
  ('Kopi itu seperti kehidupan, terkadang pahit di awal tapi manis di akhir jika kamu sabar menikmatinya.', 'Barista Bijak', 'Kopi', true),
  ('Jangan bandingkan prosesmu dengan highlight orang lain. Mereka juga punya chapter yang tidak mereka share.', 'Anonim', 'Refleksi', true),
  ('Shift malam itu bukan hukuman, itu adalah waktu di mana dunia tidur dan kamu bertumbuh.', 'Pekerja Malam', 'Kehidupan', true),
  ('Kadang hal terbaik yang bisa kamu lakukan bukan menyelesaikan semua masalah, tapi cukup hadir dan bertahan.', 'Kelas Pekerja', 'Filosofi', true),
  ('Kopi tidak akan menyelesaikan masalahmu, tapi setidaknya kamu akan lebih kuat untuk menghadapinya.', 'Pecinta Kopi', 'Kopi', true),
  ('Setiap shift yang selesai adalah kemenangan kecil yang layak dirayakan dengan secangkir kopi.', 'Kelas Pekerja', 'Kehidupan', true),
  ('Jangan lupa istirahat. Bukan karena kamu lemah, tapi karena kamu butuh mengisi ulang untuk tetap kuat.', 'Self-Care', 'Refleksi', true);
